Addin source master

diff --git a/data/client-functions b/data/client-functions
--- a/data/client-functions
+++ b/data/client-functions
@@ -1,27 +1,11 @@
-#!/bin/sh
-###########################################################################
+# /bin/sh -n
+# This file is part of Epoptes, https://epoptes.org
+# Copyright (C) 2010-2023 the Epoptes team, see AUTHORS
+# SPDX-License-Identifier: GPL-3.0-or-later
+#
 # Implements the client side of the epoptes communications protocol.
 # The daemon reads this file when it starts, and sends it to clients when they
 # connect. The clients actually source it and then wait for further commands.
-#
-# Copyright (C) 2010-2015 Alkis Georgopoulos <alkisg@gmail.com>
-#
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-#
-# On Debian GNU/Linux systems, the complete text of the GNU General
-# Public License can be found in `/usr/share/common-licenses/GPL'.
-###########################################################################
 
 # Dash handles signals a bit differently from bash.
 # We need to trap both 0 and 15 otherwise the trap function isn't called at all.
@@ -37,14 +21,17 @@ on_signal() {
     code="$?"
     trap - 0 15
     # Don't relaunch if the system is shutting down
-    if [ "$UID" -eq 0 ] && [ -d /run/systemd/system ] && [ -x /bin/systemctl ] \
-        && systemctl list-jobs | grep -q 'shutdown.target[[:space:]]*start'
-    then
+    if [ "$UID" -eq 0 ] && [ -d /run/systemd/system ] && [ -x /bin/systemctl ] &&
+        systemctl list-jobs | grep -q 'shutdown.target[[:space:]]*start'; then
         echo "epoptes-client got signal: $1, but system is shutting down" >&5
     else
         echo "epoptes-client got signal: $1, relaunching..." >&5
         # Restore the stdio descriptors to the previously saved 5
-        ( sleep 10; ping; exec epoptes-client $SERVER $PORT >&5 2>&1; ) &
+        (
+            sleep 10
+            ping
+            exec epoptes-client $SERVER $PORT >&5 2>&1
+        ) &
     fi
     exit "$code"
 }
@@ -53,7 +40,7 @@ on_signal() {
 # Parameters:
 # $1..$N = The message.
 die() {
-    echo "epoptes-client ERROR: $@" >&5
+    echo "epoptes-client ERROR: $*" >&5
     trap - 0 15
     exit 1
 }
@@ -64,7 +51,7 @@ ensure_display() {
     local vars
 
     test "$UID" -eq 0 || return 0
-    if xwininfo -root -size >/dev/null 2>&1; then
+    if timeout 1 xprop -root EPOPTES_CLIENT >/dev/null 2>&1; then
         return 0
     elif vars=$(./get-display); then
         export $vars
@@ -84,6 +71,50 @@ xprop_get() {
 
 xprop_unset() {
     xprop -root -remove "$1"
+}
+
+# Get the main MAC address, avoiding bonds, MAC randomization etc (#178).
+main_mac() {
+    local resi resm resp line iface priority
+
+    # Result interface, mac and priority
+    unset resi resm
+    resp=0
+    while read -r line; do
+        set -o noglob
+        # shellcheck disable=SC2086
+        set -- $line
+        set +o noglob
+        iface=${2%:}
+        shift 2
+        case "$iface" in
+        # "Child" interfaces like enp3s0.5@enp3s0
+        *[.@]*) priority=1 ;;
+        # Possibly ethernet
+        e*) priority=4 ;;
+        # Possibly wireless
+        w*) priority=3 ;;
+        # Anything else, bond, tap, vmbr, fwbr
+        *) priority=2 ;;
+        esac
+        unset mac
+        while [ $# -gt 1 ]; do
+            case "$1" in
+            link/ether) mac=$2 ;;
+            # Bonds, MAC randomization and in general "Cloned MAC"
+            permaddr) mac=$2 ;;
+            esac
+            shift
+        done
+        if [ -n "$mac" ] && [ "$priority" -gt "$resp" ]; then
+            resi=$iface
+            resm=$mac
+            resp=$priority
+        fi
+    done <<EOF
+$(ip -oneline -family inet link show | LANG=C sort -k 2,2)
+EOF
+    echo "$resm $resi"
 }
 
 # Calculate, export and return a collection of useful variables.
@@ -108,27 +139,34 @@ info() {
         else
             server_ip=$(getent hosts "$SERVER" | awk '{ print $1; exit }')
             server_ip=${server_ip:-$SERVER}
-            read def_iface IP <<EOF
+            read -r def_iface IP <<EOF
 $(ip route get "$server_ip" | sed -n 's/.*dev *\([^ ]*\).*src *\([^ ]*\).*/\1 \2/p')
 EOF
-            test "${def_iface:-lo}" != "lo" || read def_iface IP <<EOF
+            test "${def_iface:-lo}" != "lo" || read -r def_iface IP <<EOF
 $(ip route get 192.168.67.0 | sed -n 's/.*dev *\([^ ]*\).*src *\([^ ]*\).*/\1 \2/p')
 EOF
             test "${def_iface:-lo}" != "lo" || die "Empty def_iface"
             test -n "$IP" || die "Empty IP"
-            MAC=$(ip link show dev "$def_iface" |
-                awk '/ether/ { print tolower($2) }')
-            # Some interfaces might not have a MAC (e.g. tun), use a fallback
-            test -n "$MAC" || MAC=$(ip link show |
-                awk '/ether/ { print tolower($2); exit }')
+            MAC=$(main_mac)
+            MAC=${MAC%% *}
             test -n "$MAC" || die "Empty MAC"
         fi
-        CPU=$(awk -F': ' '/^model name/ { print $2; exit }' /proc/cpuinfo)
+        CPU=$(awk -F': ' '/^(model name|Model)/ { print $2; exit }' /proc/cpuinfo)
+        # Avoid the name "GROUPS" as it's an internal bash variable, see
+        # https://github.com/ltsp/ltsp/issues/389#issuecomment-1144856545
+        MEMBEROF=$(groups | tr ' ' ',')
         RAM=$(awk '/^MemTotal:/ { print int($2/1024) }' /proc/meminfo)
-        VGA=$(lspci -nn -m 2>/dev/null | sed -n -e '/"VGA/s/[^"]* "[^"]*" "[^"]*" "\([^"]*\)" .*/\1/p' | tr '\n' ' ')
+        # Use grep to avoid syntax errors like e.g. this on rpi4:
+        # MODALIAS=of:NgpuT(null)Cbrcm,bcm2711-vc5
+        VGA=$(
+            DRIVER=
+            PCI_ID=
+            eval "$(grep -shE '^(DRIVER|PCI_ID)=' /sys/class/graphics/fb?/../../uevent  /sys/class/drm/card?/../../uevent || true)"
+            echo "$DRIVER${PCI_ID:+" [$PCI_ID]"}"
+        )
         OS=$(uname -o)
 
-        export VERSION USER NAME HOME HOSTNAME IP MAC CPU RAM VGA OS
+        export VERSION USER NAME HOME MEMBEROF HOSTNAME IP MAC CPU RAM VGA OS
         cached_info=true
     fi
     cat <<EOF
@@ -138,6 +176,7 @@ version=$VERSION
 user=$USER
 name=$NAME
 home=$HOME
+memberof=$MEMBEROF
 hostname=$HOSTNAME
 mac=$MAC
 ip=$IP
@@ -164,7 +203,11 @@ background() {
     # /dev/null, so that it doesn't interfere with the output of other commands.
     # stderr isn't changed, i.e. ~/.xsession-errors will be used.
     # See issues #58 and #103 for explanation of the following syntax.
-    ( unset DESKTOP_AUTOSTART_ID; exec 0</dev/null >/dev/null; "$@" ) &
+    (
+        unset DESKTOP_AUTOSTART_ID
+        exec 0</dev/null >/dev/null
+        "$@"
+    ) &
 
     test -n "$print_pid" && echo $!
 }
@@ -179,29 +222,29 @@ execute() {
     echo "$(LANG=C date '+%c'), epoptes-client executing: $1" >&5
 
     case "$1" in
-        '')
-            echo "Can't execute an empty command." >&5
-            ;;
-        www.*)
-            set "http://$1"
+    '')
+        echo "Can't execute an empty command." >&5
+        ;;
+    www.*)
+        set "http://$1"
+        launcher="xdg-open"
+        ;;
+    http:* | https:* | ftp:* | file:* | mailto:*)
+        launcher="xdg-open"
+        ;;
+    *)
+        if [ -e "$1" ] && { [ ! -x "$1" ] || [ -d "$1" ]; }; then
             launcher="xdg-open"
-            ;;
-        http:*|https:*|ftp:*|file:*|mailto:*)
-            launcher="xdg-open"
-            ;;
-        *)
-            if [ -e "$1" ] && ( [ ! -x "$1" ] || [ -d "$1" ] ); then
-                launcher="xdg-open"
-            elif which -- "$1" >/dev/null; then
-                # Don't waste RAM for sh if it's just an executable.
-                launcher=""
-            fi
+        elif which -- "$1" >/dev/null; then
+            # Don't waste RAM for sh if it's just an executable.
+            launcher=""
+        fi
+        ;;
     esac
     # In all unhandled cases, run the command with sh -c.
     launcher=${launcher-sh -c}
     background $launcher "$1"
 }
-
 
 # Log out the connected user.
 logout() {
@@ -226,13 +269,14 @@ thumbshot() {
     # TODO: remove compatibility fallback after a few versions
     local executable
 
+    test -z "$WAYLAND_DISPLAY" || return 0
     if [ -f "./thumbshot.py" ]; then
         executable=./thumbshot.py
     else
         executable=./screenshot
     fi
     if ! $executable "$1" "$2"; then
-        BAD_THUMBSHOTS=$(($BAD_THUMBSHOTS+1))
+        BAD_THUMBSHOTS=$((BAD_THUMBSHOTS + 1))
         echo "$BAD_THUMBSHOTS failed thumbshots so far!" >&5
     fi
 }
@@ -247,9 +291,10 @@ lock_screen() {
     unlock_screen
     # TODO: remove compatibility fallback after a few versions
     if [ -f "./lock_screen.py" ]; then
-        pid=$(background -p ./lock_screen.py "$2")
+        pid=$(background -p exec ./lock_screen.py "$2")
     else
-        pid=$(background -p ./lock-screen "$2")
+        # exec is needed to return the correct pid when /bin/sh -> bash
+        pid=$(background -p exec ./lock-screen "$2")
     fi
     xprop_set EPOPTES_LOCK_SCREEN_PID "$pid"
 }
@@ -290,20 +335,26 @@ unmute_sound() {
 # Stop it automatically after a while.
 # Before starting, also stop any previous benchmarks that are still running.
 # Parameters:
-# $1 = seconds to run (default=10).
+# $1 = host
+# $2 = seconds to run (default=10).
 start_benchmark() {
     # benchmark_pid can't be unset in the background, but no harm done
     benchmark_pid=$(background -p stop_start_benchmark "$@")
-    { sleep $((2*${1:-10}+5)); stop_benchmark "$benchmark_pid"; } &
+    {
+        sleep $((2 * ${2:-10} + 5))
+        stop_benchmark "$benchmark_pid"
+    } &
     echo "$benchmark_pid"
 }
 
 # Helper function to avoid running stop_benchmark in foreground.
 # Parameters:
-# $1 = seconds to run.
+# $1 = host
+# $2 = seconds to run.
 stop_start_benchmark() {
     test -n "$benchmark_pid" && stop_benchmark "$benchmark_pid"
-    iperf -c "$SERVER" -r ${1:+-t "$1"}
+    # exec is needed to return the correct pid when /bin/sh -> bash
+    exec iperf -c "$1" --full-duplex ${1:+-t "$2"}
 }
 
 # Manually stop a previously running benchmark.
@@ -338,17 +389,17 @@ message() {
 
 # Connect to the server to be monitored.
 # Parameters:
-# $1 = port.
+# $1 = host:port.
 get_monitored() {
-    background x11vnc -noshm -24to32 -viewonly -connect_or_exit "$SERVER:$1"
+    background x11vnc -q -nopw -noshm -24to32 -viewonly -connect_or_exit "$1"
 }
 
 # Connect to the server to get assistance.
 # Parameters:
-# $1 = port.
+# $1 = host:port.
 # $2 = grab keyboard and mouse.
 get_assisted() {
-    background x11vnc -noshm -24to32 ${2:+-grabptr -grabkbd} -connect_or_exit "$SERVER:$1"
+    background x11vnc -q -nopw -noshm -24to32 ${2:+-grabptr -grabkbd} -connect_or_exit "$1"
 }
 
 # Deactivate the screensaver, in order for the users to watch a broadcast.
@@ -362,38 +413,63 @@ reset_screensaver() {
 
 # Receive a broadcasted screen from the server.
 # Parameters:
-# $1 = port.
+# $1 = host:port.
 # $2 = password (encrypted as in ~/.vnc/passwd and octal-escaped).
 # $3 = fullscreen.
 receive_broadcast() {
     receiving_broadcast=true
     stop_receptions
     reset_screensaver
+    # See https://epoptes.org/documentation/vnc/
     if [ -z "$VNCVIEWER" ]; then
-        # If the user installed ssvnc, prefer it over xvnc4viewer
-        if [ -x /usr/bin/ssvncviewer ]; then
+        if [ -f /usr/share/applications/realvnc-vncviewer.desktop ]; then
+            VNCVIEWER=realvnc-vnc-viewer
+        elif [ -x /usr/bin/ssvncviewer ]; then
             VNCVIEWER=ssvncviewer
-        elif [ -x /usr/bin/xtigervncviewer ]; then
-            VNCVIEWER=xtigervncviewer
-        elif [ -x /usr/bin/xvnc4viewer ]; then
-            VNCVIEWER=xvnc4viewer
+        else
+            VNCVIEWER=$(readlink -f /usr/bin/vncviewer)
+            VNCVIEWER=${VNCVIEWER##*/}
         fi
     fi
+    # shellcheck disable=SC2059  # $2 is octal-escaped
     printf "$2" | {
-        sleep 0.$(($(hexdump -e \"%d\" -n 2 /dev/urandom) % 50 + 50))
-        if [ "$VNCVIEWER" = "ssvncviewer" ]; then
-            exec ssvncviewer -shared -viewonly -passwd /dev/stdin \
-                ${3:+-fullscreen} "$SERVER:$1"
-        elif [ "$VNCVIEWER" = "xvnc4viewer" ]; then
-            exec ${VNCVIEWER} -Shared -ViewOnly -passwd /dev/stdin \
-                ${3:+-FullScreen -UseLocalCursor=0 -MenuKey F13} "$SERVER:$1"
-        elif [ "$VNCVIEWER" = "xtigervncviewer" ]; then
-            exec ${VNCVIEWER} -Shared -ViewOnly -passwd /dev/stdin \
-                ${3:+-FullScreen -MenuKey F13} "$SERVER:$1"
-        else
-            exec vncviewer -shared -viewonly -passwd /dev/stdin \
-                ${3:+-fullscreen} "$SERVER:$1"
-        fi
+        sleep 0.$(($(od -An -N2 -tu2 /dev/urandom) % 50 + 50))
+        case "$VNCVIEWER" in
+        realvnc-vnc-viewer)
+            if [ -f "/etc/epoptes/vncviewer" ] &&
+                [ ! -f "$HOME/.vnc/config.d/vncviewer" ]; then
+                mkdir -pm 700 "$HOME/.vnc"
+                mkdir -pm 700 "$HOME/.vnc/config.d"
+                cp /etc/epoptes/vncviewer "$HOME/.vnc/config.d/vncviewer"
+            fi
+            exec vncviewer -shared -viewonly -securitynotificationtimeout=0 \
+                -scaling=aspectfit -uselocalcursor=0 \
+                -enabletoolbar=0 -warnunencrypted=0 \
+                -hideclosealert=true -autoreconnect=false \
+                -passwd /dev/stdin ${3:+-fullscreen -menukey=} "$1"
+            ;;
+        ssvncviewer)
+            exec ssvncviewer -shared -viewonly -scale auto -escape never \
+                -passwd /dev/stdin ${3:+-fullscreen} "$1"
+            ;;
+        xtigervncviewer)
+            exec xtigervncviewer -shared -viewonly \
+                -passwd /dev/stdin ${3:+-fullscreen -menukey=} "$1"
+            ;;
+        xtightvncviewer)
+            exec xtightvncviewer -shared -viewonly \
+                -passwd /dev/stdin ${3:+-fullscreen} "$1"
+            ;;
+        xvnc4viewer)
+            exec xvnc4viewer -shared -viewonly -uselocalcursor=0 \
+                -passwd /dev/stdin ${3:+-fullscreen -menukey=} "$1"
+            ;;
+        *)
+            # A generic vncviewer, e.g. tigervnc on Arch/Fedora/SUSE
+            exec "$VNCVIEWER" -shared -viewonly \
+                -passwd /dev/stdin ${3:+-fullscreen} "$1"
+            ;;
+        esac
     } >/dev/null 2>&1 &
     xprop_set EPOPTES_VNCVIEWER_PID "$!"
 }
@@ -417,9 +493,9 @@ root_term() {
     background xterm -e bash -l
 }
 
-# Send a screen session to the server using socat.
+# Send a screen session to a host using socat.
 # Parameters:
-# $1 = port.
+# $1 = host:port.
 remote_term() {
     local screen_params
 
@@ -431,7 +507,7 @@ remote_term() {
     background sh -c "
 cd
 sleep 1
-TERM=xterm exec socat EXEC:'screen $screen_params',pty,stderr tcp:$SERVER:$1"
+TERM=xterm exec socat EXEC:'screen $screen_params',pty,stderr tcp:$1"
 }
 
 # Ping is called every few seconds just to make sure the connection is alive.
diff --git a/epoptes-client/epoptes-client b/epoptes-client/epoptes-client
--- a/epoptes-client/epoptes-client
+++ b/epoptes-client/epoptes-client
@@ -1,6 +1,6 @@
 #!/bin/sh
 # This file is part of Epoptes, https://epoptes.org
-# Copyright 2010-2018 the Epoptes team, see AUTHORS.
+# Copyright 2010-2023 the Epoptes team, see AUTHORS.
 # SPDX-License-Identifier: GPL-3.0-or-later
 
 # epoptes-client is called either from systemd as root, to control the client,
@@ -8,18 +8,18 @@
 # Users can cancel that from their System > Preferences > Services gnome menu.
 
 usage() {
-    printf "Usage: $0 [-c|-h|-v] [SERVER] [PORT]\n%s" \
-'
+    cat <<EOF
+Usage: $0 [-c|-h|-v] [SERVER] [PORT]
 Connect to a remote server and offer it a local shell.
-'
+EOF
 }
 
 version() {
-    export VERSION="1.0"  # Automatically updated while packaging
+    export VERSION="1.0" # Automatically updated while packaging
 }
 
 die() {
-    echo "epoptes-client ERROR: $@" >&2
+    echo "epoptes-client ERROR: $*" >&2
     exit 1
 }
 
@@ -27,9 +27,9 @@ die() {
 # from sourcing ltsp_common_functions. So we're using a different name.
 my_boolean_is_true() {
     case "$1" in
-       # match all cases of true|y|yes
-       [Tt][Rr][Uu][Ee]|[Yy]|[Yy][Ee][Ss]) return 0 ;;
-       *) return 1 ;;
+    # match all cases of true|y|yes
+    [Tt][Rr][Uu][Ee] | [Yy] | [Yy][Ee][Ss]) return 0 ;;
+    *) return 1 ;;
     esac
 }
 
@@ -40,8 +40,7 @@ chrooted() {
     test -n "$UID" || UID=$(id -u)
     if [ "$UID" -gt 0 ]; then
         chrooted=1
-    elif [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ]
-    then
+    elif [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ]; then
         # the devicenumber/inode pair of / is the same as that of /sbin/init's
         # root, so we're *not* in a chroot and hence return false.
         chrooted=1
@@ -60,26 +59,26 @@ basic_info() {
     # not in our environment, and we need to source ltsp_config.
     # But we don't want to pollute the environment with any of its other vars.
     if [ "$UID" -eq 0 ] && [ -f /usr/share/ltsp/ltsp_config ] && ! chrooted &&
-        egrep -qs 'ltsp|nfs|nbd' /proc/cmdline
-    then
+        grep -Eqs 'ltsp|nfs|nbd' /proc/cmdline; then
+        # shellcheck disable=SC2046
         export $(
             . /usr/share/ltsp/ltsp_config >/dev/null
             echo "LTSP_CLIENT=$LTSP_CLIENT"
             echo "LTSP_FATCLIENT=$LTSP_FATCLIENT"
-            echo "EPOPTES_CLIENT_VERIFY_CERTIFICATE=$EPOPTES_CLIENT_VERIFY_CERTIFICATE")
-        # LTSP_CLIENT may not be available in system sesssions, if so fake it
+            echo "EPOPTES_CLIENT_VERIFY_CERTIFICATE=$EPOPTES_CLIENT_VERIFY_CERTIFICATE"
+        )
+        # LTSP_CLIENT may not be available in system sessions, if so fake it
         LTSP_CLIENT=${LTSP_CLIENT:-127.0.0.1}
     fi
 
     # LTSP_FATCLIENT may not be available in user sessions, autodetect it
     if [ -n "$LTSP_CLIENT" ] && [ -z "$LTSP_FATCLIENT" ] &&
         [ "$UID" -gt 0 ] && [ -x /usr/bin/getltscfg ] &&
-        egrep -qs 'ltsp|nfs|nbd' /proc/cmdline
-    then
+        grep -Eqs 'ltsp|nfs|nbd' /proc/cmdline; then
         LTSP_FATCLIENT=True
     fi
 
-    if my_boolean_is_true "$LTSP_FATCLIENT"; then
+    if my_boolean_is_true "$LTSP_FATCLIENT" || [ -d /run/ltsp/client ]; then
         TYPE="fat"
     elif [ -n "$LTSP_CLIENT" ]; then
         TYPE="thin"
@@ -87,7 +86,7 @@ basic_info() {
         TYPE="standalone"
     fi
 
-    if ( [ "$TYPE" = "thin" ] && [ "$UID" -gt 0 ] ) || chrooted; then
+    if { [ "$TYPE" = "thin" ] && [ "$UID" -gt 0 ]; } || chrooted; then
         SERVER=localhost
     else
         SERVER=server
@@ -97,128 +96,157 @@ basic_info() {
     export UID TYPE SERVER PORT
 }
 
-fetch_certificate()
-{
+fetch_certificate() {
+    local contents
+
     test "$UID" -eq 0 || die "Need to be root to fetch the certificate"
     mkdir -p /etc/epoptes
-    openssl s_client -connect $SERVER:$PORT < /dev/null \
-        | sed '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/!d' \
-        > /etc/epoptes/server.crt
-    if [ -s /etc/epoptes/server.crt ]; then
+    # First fetch, then store, to avoid zeroing the output file
+    if contents=$(openssl s_client -connect $SERVER:$PORT </dev/null |
+        sed '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/!d') &&
+        [ -n "$contents" ]; then
+        echo "$contents" >/etc/epoptes/server.crt
         echo "Successfully fetched certificate from $SERVER:$PORT"
-        exit 0
     else
         die "Failed to fetch certificate from $SERVER:$PORT"
     fi
 }
 
+re() {
+    "$@" || echo die "Command failed: $*"
+}
+
 wait_for_dns() {
+    local delay
+
     # Don't wait for DNS if SERVER is an IP
-    if [ -z "$(echo "$SERVER" | tr -d '[0-9.]')" ]; then
+    if [ -z "$(echo "$SERVER" | tr -d '0-9.')" ]; then
         server_ip=$SERVER
         return
     fi
-    delay=60
+    delay=5
     while true; do
         server_ip=$(getent hosts "$SERVER" | awk '{ print $1; exit }')
         test -n "$server_ip" && break
-        # If DNS is not up yet, retry, otherwise abort
-        server_ip=$(getent hosts "ntp.org" | awk '{ print $1; exit }')
-        if [ -z "$server_ip" ]; then
-            echo "Cannot resolve $SERVER, postponing for $delay seconds..."
-            sleep $delay
-            # Add a minute for each failure to minimize log spamming
-            delay=$(($delay+60))
-        else
+        # If DNS is up and SERVER is not an MDNS name, abort
+        if [ "${SERVER%.local}" = "${SERVER}" ] &&
+            [ -n "$(getent hosts "ntp.org" | awk '{ print $1; exit }')" ]; then
             echo "Cannot resolve $SERVER while DNS appears to work, aborting."
             exit 1
+        fi
+        if [ "$delay" -eq 5 ]; then
+            echo "Cannot resolve $SERVER, will keep retrying."
+        fi
+        sleep $delay
+        # Increase delay up to a minute
+        if [ "$delay" -lt 60 ]; then
+            delay=$((delay + 1))
         fi
     done
 }
 
+# Set WoL to the desired state for all currently available Ethernet adapters
 apply_wol() {
-    if [ "$UID" -eq 0 ] && [ -n "$WOL" ] && [ -x /sbin/ethtool ] &&
-        [ "$EPOPTES_CLIENT_APPLIED_WOL" != True ]
-    then
-        export EPOPTES_CLIENT_APPLIED_WOL=True
-        # Copied from client-functions, these map from server_ip to def_iface
-        read def_iface IP <<EOF
-$(ip route get "$server_ip" | sed -n 's/.*dev *\([^ ]*\).*src *\([^ ]*\).*/\1 \2/p')
-EOF
-        test "${def_iface:-lo}" != "lo" || read def_iface IP <<EOF
-$(ip route get 192.168.67.0 | sed -n 's/.*dev *\([^ ]*\).*src *\([^ ]*\).*/\1 \2/p')
-EOF
-        if [ "${def_iface:-lo}" != "lo" ]; then
-            # Only set WOL if def_iface is both != '' and != 'lo'.
-            echo "Setting WOL=$WOL for $def_iface"
-            ethtool -s "$def_iface" wol $WOL
-        fi
-    fi
-}
+    local tarwol fpath iface curwol
 
+    test "$UID" -eq 0 || return 0
+    # Set target WOL to "g" if WOL is unset
+    tarwol=${WOL-g}
+    # Return if WOL="ignore" or WOL=""
+    test "${tarwol:-ignore}" != "ignore" || return 0
+    test -x /sbin/ethtool || return 0
+    # Only handle devices with a physical MAC address
+    for fpath in /sys/class/net/*/device/net/*/address; do
+        test -f "$fpath" || continue
+        iface=${fpath%/address}
+        iface=${iface##*/}
+        # Avoid setting it again if it's already set
+        curwol=$(ethtool "$iface" | awk '$1 == "Wake-on:" { print $2 }')
+        test "$curwol" != "$tarwol" || continue
+        if ethtool -s "$iface" wol "$tarwol"; then
+            echo "Set WOL=$tarwol for $iface"
+        else
+            echo "Failed to set WOL=$tarwol for $iface"
+        fi
+    done
+}
 
 # Main.
 version
 
 # Check the first parameter as it may turn out we don't need to run at all
 case "$1" in
-    -v|--version)
-        echo "$VERSION"
+-v | --version)
+    echo "$VERSION"
+    exit
+    ;;
+-h | --help)
+    if [ -x /usr/bin/man ]; then
+        exec man epoptes-client
+    else
+        usage
         exit
-        ;;
-    -h|--help)
-        if [ -x /usr/bin/man ]; then
-            exec man epoptes-client
-        else
-            usage
-            exit
-        fi
-        ;;
-    -c|--certificate)
-        need_certificate=true
-        shift
-        ;;
+    fi
+    ;;
+-c | --certificate)
+    need_certificate=true
+    shift
+    ;;
 esac
 
 # Set a reasonable PATH to execute commands or to relaunch epoptes-client.
 export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
 
 # When launched as a service, LANG might not be set.
-if [ -z "$LANG" ] && [ -r /etc/default/locale ]; then
-    . /etc/default/locale
-    export LANG
-fi
+for conf in /etc/default/locale /etc/locale.conf; do
+    if [ -z "$LANG" ] && [ -f "$conf" ]; then
+        . "$conf"
+        export LANG
+    fi
+done
 
 basic_info
-# The configuration file overrides the default values
-if [ -f /etc/default/epoptes-client ]; then
-    . /etc/default/epoptes-client
-fi
+# The configuration files override the default values
+for conf in /etc/default/epoptes-client \
+    /etc/epoptes/common/*.conf \
+    /etc/epoptes/client/*.conf; do
+    if [ -f "$conf" ]; then
+        . "$conf" || true
+    fi
+done
 # And the command line parameters override the configuration file
-export SERVER=${1:-$SERVER}
-export PORT=${2:-$PORT}
+export "SERVER=${1:-$SERVER}"
+export "PORT=${2:-$PORT}"
 
 # Provide an easy way to fetch the server certificate
 test -n "$need_certificate" && fetch_certificate
 
-# We don't want the epoptes-client system service running on the epoptes server
-if ( [ $UID -eq 0 ] && [ $TYPE = "standalone" ] && [ -x /usr/bin/epoptes ] ) ||
-    chrooted
-then
+servercrt=/etc/epoptes/server.crt
+# Don't launch as root on epoptes servers, unless there's a main server
+if [ "$UID" -eq 0 ] && [ $TYPE = "standalone" ] && [ -x /usr/bin/epoptes ]; then
+    if [ -s /etc/epoptes/main-server.crt ]; then
+        servercrt=/etc/epoptes/main-server.crt
+        SERVER=${MAIN_SERVER:-main-server}
+    else
+        exit 0
+    fi
+fi
+# Don't launch inside chroots
+if chrooted; then
     exit 0
 fi
 
 # Go to the scripts directory, so that we can run them with ./xxx
-cd $(dirname "$0")
+re cd "$(dirname "$0")"
 if [ -d ../epoptes-client ]; then
-    cd ../epoptes-client
+    re cd ../epoptes-client
 else
-    cd /usr/share/epoptes-client
+    re cd /usr/share/epoptes-client
 fi
 
 wait_for_dns
 apply_wol
-printf "Epoptes-client connecting to $SERVER:$PORT..."
+printf "Epoptes-client connecting to %s:%s..." "$SERVER" "$PORT"
 
 # Call chain:
 #  * systemd executes /usr/sbin/epoptes-client
@@ -243,11 +271,13 @@ cmdline='bash -c \"exec -a epoptes-client sh\"'
 
 # Offer an lts.conf (or environment) variable to disable cert verification.
 if my_boolean_is_true "${EPOPTES_CLIENT_VERIFY_CERTIFICATE:-True}"; then
-    cert_param="cafile=/etc/epoptes/server.crt"
-    # Check if socat provides the commonname option and use it in order to
-    # support certificates which don't have a commonname set
-    if socat -hhh | grep -q openssl-commonname; then
-        cert_param="$cert_param,commonname=\"\""
+    cert_param="cafile=$servercrt"
+    # Support certificates without or with changed hostname
+    if socat -hhh | grep -qw openssl-no-sni; then
+        cert_param="$cert_param,openssl-no-sni"
+    fi
+    if socat -hhh | grep -qw openssl-commonname; then
+        cert_param="$cert_param,openssl-commonname=\"\""
     fi
 else
     cert_param="verify=0"
@@ -255,13 +285,13 @@ fi
 
 # Connect to the server, or keep retrying until the server gets online
 # (for standalone workstations booted before the server).
-if [ -s /etc/epoptes/server.crt ] || [ "$cert_param" = "verify=0" ]; then
-    exec socat -T 60 openssl-connect:$SERVER:$PORT,$cert_param,interval=60,forever EXEC:"$cmdline"
-elif [ -f /etc/epoptes/server.crt ]; then
-   exec socat tcp:$SERVER:$PORT,interval=60,forever EXEC:"$cmdline",nofork
+if [ -s "$servercrt" ] || [ "$cert_param" = "verify=0" ]; then
+    exec socat -T 60 "openssl-connect:$SERVER:$PORT,$cert_param,interval=60,forever" "EXEC:$cmdline"
+elif [ -f "servercrt" ]; then
+    exec socat "tcp:$SERVER:$PORT,interval=60,forever" "EXEC:$cmdline,nofork"
 else
     die "
-The epoptes certificate file, /etc/epoptes/server.crt, doesn't exist.
+The epoptes certificate file, $servercrt, doesn't exist.
 You can fetch the server certificate by running:
 $0 -c"
 fi
