Updated to version 20.01-1~ubuntu20.04.1

diff --git a/data/client-functions b/data/client-functions
--- a/data/client-functions
+++ b/data/client-functions
@@ -1,9 +1,10 @@
+#!/bin/sh
 ###########################################################################
 # Implements the client side of the epoptes communications protocol.
 # The daemon reads this file when it starts, and sends it to clients when they
 # connect. The clients actually source it and then wait for further commands.
 #
-# Copyright (C) 2010, 2012 Alkis Georgopoulos <alkisg@gmail.com>
+# Copyright (C) 2010-2015 Alkis Georgopoulos <alkisg@gmail.com>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -22,12 +23,67 @@
 # Public License can be found in `/usr/share/common-licenses/GPL'.
 ###########################################################################
 
+# Dash handles signals a bit differently from bash.
+# We need to trap both 0 and 15 otherwise the trap function isn't called at all.
+# 0 is normal program termination, it's called on `service epoptes restart`.
+# 15 is SIGTERM, it's called when socat reaches the -T timeout.
+# We don't always want to relaunch though.
+# For user sessions, ping() aborts when X isn't running.
+# Root connections abort when the system is shutting down.
+# Also, epoptes-client kills -QUIT all the other epoptes-client processes.
+on_signal() {
+    # local code  # we can't do that, it resets $?
+
+    code="$?"
+    trap - 0 15
+    # Don't relaunch if the system is shutting down
+    if [ "$UID" -eq 0 ] && [ -d /run/systemd/system ] && [ -x /bin/systemctl ] \
+        && systemctl list-jobs | grep -q 'shutdown.target[[:space:]]*start'
+    then
+        echo "epoptes-client got signal: $1, but system is shutting down" >&5
+    else
+        echo "epoptes-client got signal: $1, relaunching..." >&5
+        # Restore the stdio descriptors to the previously saved 5
+        ( sleep 10; ping; exec epoptes-client $SERVER $PORT >&5 2>&1; ) &
+    fi
+    exit "$code"
+}
+
 # Output a message and exit with an error.
 # Parameters:
 # $1..$N = The message.
-die() { 
-    echo "epoptes-client ERROR: $@" >&2
+die() {
+    echo "epoptes-client ERROR: $@" >&5
+    trap - 0 15
     exit 1
+}
+
+# Some actions like broadcasting need access to the display even if they
+# run as root. Xorg might have been restarted though, so detect DISPLAY.
+ensure_display() {
+    local vars
+
+    test "$UID" -eq 0 || return 0
+    if xwininfo -root -size >/dev/null 2>&1; then
+        return 0
+    elif vars=$(./get-display); then
+        export $vars
+    else
+        return 1
+    fi
+}
+
+xprop_set() {
+    xprop -root -f "$1" 8u -set "$1" "$2"
+}
+
+xprop_get() {
+    # xprop -root UNSET_VAR echoes an error message to stdout instead of stderr
+    xprop -root "$1" 2>/dev/null | sed 's/^[^=]*//;s/^= "//;s/"$//;s/\\"/"/'
+}
+
+xprop_unset() {
+    xprop -root -remove "$1"
 }
 
 # Calculate, export and return a collection of useful variables.
@@ -47,29 +103,32 @@ info() {
         fi
         if [ -n "$LTSP_CLIENT" ] && [ -n "$LTSP_CLIENT_MAC" ]; then
             # LTSP exports those vars, use them if available.
-            MAC="$LTSP_CLIENT_MAC"
+            MAC=$(echo "$LTSP_CLIENT_MAC" | awk '{ print tolower($1) }')
             IP="$LTSP_CLIENT"
         else
-            server_ip=$(getent hosts "$SERVER" | cut -d' ' -f1)
-            def_iface=$(ip -oneline -family inet route get "$server_ip" \
-                | sed -n '/.* dev \([^ ]*\).*/s//\1/p')
-            test "${def_iface:-lo}" = "lo" && def_iface=$(ip -oneline -family \
-                inet route show | sed -n '/^default .* dev \([^ ]*\).*/s//\1/p')
-            def_iface=${def_iface:-eth0}
-            MAC=$(ip -oneline -family inet link show dev "$def_iface" \
-                | sed "s/.*ether \([^ ]*\).*/\\1/")
-            MAC=$(echo "$MAC" | sed 'y/abcdef-/ABCDEF:/;s/[^A-F0-9:]//g')
-            test -n "$MAC" || die "Empty MAC"
-            IP=$(ip -oneline -family inet addr show dev "$def_iface" \
-                | sed "s/.* \([0-9.]*\)\/.*/\\1/")
+            server_ip=$(getent hosts "$SERVER" | awk '{ print $1; exit }')
+            server_ip=${server_ip:-$SERVER}
+            read def_iface IP <<EOF
+$(ip route get "$server_ip" | sed -n 's/.*dev *\([^ ]*\).*src *\([^ ]*\).*/\1 \2/p')
+EOF
+            test "${def_iface:-lo}" != "lo" || read def_iface IP <<EOF
+$(ip route get 192.168.67.0 | sed -n 's/.*dev *\([^ ]*\).*src *\([^ ]*\).*/\1 \2/p')
+EOF
+            test "${def_iface:-lo}" != "lo" || die "Empty def_iface"
             test -n "$IP" || die "Empty IP"
+            MAC=$(ip link show dev "$def_iface" |
+                awk '/ether/ { print tolower($2) }')
+            # Some interfaces might not have a MAC (e.g. tun), use a fallback
+            test -n "$MAC" || MAC=$(ip link show |
+                awk '/ether/ { print tolower($2); exit }')
+            test -n "$MAC" || die "Empty MAC"
         fi
-        CPU=$(cat /proc/cpuinfo | grep "^model name" | head -n 1 | sed "s/.*: //")
-        RAM=$(free -m | grep "^Mem" | awk '{print $2}')
-        VGA=$(lspci -nn -m | sed -n -e '/"VGA/s/[^"]* "[^"]*" "[^"]*" "\([^"]*\)" .*/\1/p' | tr '\n' ' ')
+        CPU=$(awk -F': ' '/^model name/ { print $2; exit }' /proc/cpuinfo)
+        RAM=$(awk '/^MemTotal:/ { print int($2/1024) }' /proc/meminfo)
+        VGA=$(lspci -nn -m 2>/dev/null | sed -n -e '/"VGA/s/[^"]* "[^"]*" "[^"]*" "\([^"]*\)" .*/\1/p' | tr '\n' ' ')
         OS=$(uname -o)
 
-        export VERSION USER NAME HOME HOSTNAME MAC IP CPU RAM VGA OS
+        export VERSION USER NAME HOME HOSTNAME IP MAC CPU RAM VGA OS
         cached_info=true
     fi
     cat <<EOF
@@ -96,18 +155,16 @@ EOF
 background() {
     local print_pid
 
+    ensure_display
     if [ "$1" = "-p" ]; then
         print_pid=true
         shift
     fi
-
-    # On root clients, try to get the active DISPLAY, the command may need it.
-    test "$UID" -eq 0 && export $(./get-display)
-
-    # The command is ran on a subshell with stdin and stdout redirected to
+    # The command is run on a subshell with stdin and stdout redirected to
     # /dev/null, so that it doesn't interfere with the output of other commands.
     # stderr isn't changed, i.e. ~/.xsession-errors will be used.
-    ( "$@" 0</dev/null >/dev/null ) &
+    # See issues #58 and #103 for explanation of the following syntax.
+    ( unset DESKTOP_AUTOSTART_ID; exec 0</dev/null >/dev/null; "$@" ) &
 
     test -n "$print_pid" && echo $!
 }
@@ -119,11 +176,11 @@ execute() {
     local launcher
 
     # Do some logging, either in ~/.xsession-errors or on the console.
-    echo "$(LANG=C date '+%c'), epoptes-client executing: $1" >&2
+    echo "$(LANG=C date '+%c'), epoptes-client executing: $1" >&5
 
     case "$1" in
         '')
-            echo "Can't execute an empty command." >&2
+            echo "Can't execute an empty command." >&5
             ;;
         www.*)
             set "http://$1"
@@ -161,17 +218,22 @@ shutdown() {
     ./endsession --shutdown
 }
 
-# Create a thumbnail of the user screen.
+# Create a thumbshot of the user screen.
 # Parameters:
-# $1 = thumbnail width.
-# $2 = thumbnail height.
-screenshot() {
-    if ./screenshot "$1" "$2"; then
-        BAD_SCREENSHOTS=0
-    elif [ "$BAD_SCREENSHOTS" -eq 3 ]; then
-        die "3 failed screenshots, exiting..."
+# $1 = thumbshot width.
+# $2 = thumbshot height.
+thumbshot() {
+    # TODO: remove compatibility fallback after a few versions
+    local executable
+
+    if [ -f "./thumbshot.py" ]; then
+        executable=./thumbshot.py
     else
-        BAD_SCREENSHOTS=$(($BAD_SCREENSHOTS+1))
+        executable=./screenshot
+    fi
+    if ! $executable "$1" "$2"; then
+        BAD_THUMBSHOTS=$(($BAD_THUMBSHOTS+1))
+        echo "$BAD_THUMBSHOTS failed thumbshots so far!" >&5
     fi
 }
 
@@ -180,15 +242,27 @@ screenshot() {
 # $1 = seconds to keep screen locked, 0 means forever - currently ignored.
 # $2 = message to display to the user.
 lock_screen() {
-    test -n "$EPOPTES_LOCK_SCREEN_PID" && kill "$EPOPTES_LOCK_SCREEN_PID"
-    EPOPTES_LOCK_SCREEN_PID=$(background -p ./lock-screen "$2")
+    local pid
+
+    unlock_screen
+    # TODO: remove compatibility fallback after a few versions
+    if [ -f "./lock_screen.py" ]; then
+        pid=$(background -p ./lock_screen.py "$2")
+    else
+        pid=$(background -p ./lock-screen "$2")
+    fi
+    xprop_set EPOPTES_LOCK_SCREEN_PID "$pid"
 }
 
 # Unlock a locked screen.
 unlock_screen() {
-    if [ -n "$EPOPTES_LOCK_SCREEN_PID" ]; then
-        kill "$EPOPTES_LOCK_SCREEN_PID"
-        unset EPOPTES_LOCK_SCREEN_PID
+    local pid
+
+    ensure_display
+    pid=$(xprop_get EPOPTES_LOCK_SCREEN_PID)
+    if [ -n "$pid" ]; then
+        kill "$pid"
+        xprop_unset EPOPTES_LOCK_SCREEN_PID
     fi
 }
 
@@ -212,20 +286,61 @@ unmute_sound() {
     fi
 }
 
+# Start a network benchmark and print its pid.
+# Stop it automatically after a while.
+# Before starting, also stop any previous benchmarks that are still running.
+# Parameters:
+# $1 = seconds to run (default=10).
+start_benchmark() {
+    # benchmark_pid can't be unset in the background, but no harm done
+    benchmark_pid=$(background -p stop_start_benchmark "$@")
+    { sleep $((2*${1:-10}+5)); stop_benchmark "$benchmark_pid"; } &
+    echo "$benchmark_pid"
+}
+
+# Helper function to avoid running stop_benchmark in foreground.
+# Parameters:
+# $1 = seconds to run.
+stop_start_benchmark() {
+    test -n "$benchmark_pid" && stop_benchmark "$benchmark_pid"
+    iperf -c "$SERVER" -r ${1:+-t "$1"}
+}
+
+# Manually stop a previously running benchmark.
+# Parameters:
+# $1 = pid
+stop_benchmark() {
+    if [ -n "$1" ]; then
+        kill "$1" || return 0
+        sleep 0.2
+        # For some reason, iperf -c <unknown host> needs 2 kills!
+        kill "$1" || return 0
+        sleep 0.2
+        # If it's not killed by now, it's hanged
+        kill -9 "$1" && sleep 0.2
+    fi 2>/dev/null
+}
+
 # Display some text to the user.
 # Parameters:
 # $1 = text.
 # $2 = title.
 # $3 = True/False, whether the text contains pango markup.
+# $4 = icon name.
 message() {
-    background ./message "$1" "$2" "$3"
+    # TODO: remove compatibility fallback after a few versions
+    if [ -f "./message.py" ]; then
+        background ./message.py "$@"
+    else
+        background ./message "$@"
+    fi
 }
 
 # Connect to the server to be monitored.
 # Parameters:
 # $1 = port.
 get_monitored() {
-    background x11vnc -noshm -24to32 -viewonly -connect_or_exit "$1"
+    background x11vnc -noshm -24to32 -viewonly -connect_or_exit "$SERVER:$1"
 }
 
 # Connect to the server to get assistance.
@@ -233,13 +348,15 @@ get_monitored() {
 # $1 = port.
 # $2 = grab keyboard and mouse.
 get_assisted() {
-    background x11vnc -noshm -24to32 ${2:+-grabptr -grabkbd} -connect_or_exit "$1"
+    background x11vnc -noshm -24to32 ${2:+-grabptr -grabkbd} -connect_or_exit "$SERVER:$1"
 }
 
 # Deactivate the screensaver, in order for the users to watch a broadcast.
-stop_screensaver() {
-    if [ -x /usr/bin/gnome-screensaver-command ]; then
-        gnome-screensaver-command -d
+reset_screensaver() {
+    if [ -x /usr/bin/xdg-screensaver ]; then
+        xdg-screensaver reset
+    else
+        xset s reset
     fi
 }
 
@@ -249,13 +366,15 @@ stop_screensaver() {
 # $2 = password (encrypted as in ~/.vnc/passwd and octal-escaped).
 # $3 = fullscreen.
 receive_broadcast() {
+    receiving_broadcast=true
     stop_receptions
-    test "$UID" -eq 0 && export $(./get-display)
-    xset dpms force on
+    reset_screensaver
     if [ -z "$VNCVIEWER" ]; then
         # If the user installed ssvnc, prefer it over xvnc4viewer
         if [ -x /usr/bin/ssvncviewer ]; then
             VNCVIEWER=ssvncviewer
+        elif [ -x /usr/bin/xtigervncviewer ]; then
+            VNCVIEWER=xtigervncviewer
         elif [ -x /usr/bin/xvnc4viewer ]; then
             VNCVIEWER=xvnc4viewer
         fi
@@ -264,24 +383,32 @@ receive_broadcast() {
         sleep 0.$(($(hexdump -e \"%d\" -n 2 /dev/urandom) % 50 + 50))
         if [ "$VNCVIEWER" = "ssvncviewer" ]; then
             exec ssvncviewer -shared -viewonly -passwd /dev/stdin \
-                ${3:+-fullscreen} "$1"
+                ${3:+-fullscreen} "$SERVER:$1"
         elif [ "$VNCVIEWER" = "xvnc4viewer" ]; then
-            exec xvnc4viewer -Shared -ViewOnly -passwd /dev/stdin \
-                ${3:+-FullScreen -UseLocalCursor=0 -MenuKey F13} "$1"
+            exec ${VNCVIEWER} -Shared -ViewOnly -passwd /dev/stdin \
+                ${3:+-FullScreen -UseLocalCursor=0 -MenuKey F13} "$SERVER:$1"
+        elif [ "$VNCVIEWER" = "xtigervncviewer" ]; then
+            exec ${VNCVIEWER} -Shared -ViewOnly -passwd /dev/stdin \
+                ${3:+-FullScreen -MenuKey F13} "$SERVER:$1"
         else
             exec vncviewer -shared -viewonly -passwd /dev/stdin \
-                ${3:+-fullscreen} "$1"
+                ${3:+-fullscreen} "$SERVER:$1"
         fi
     } >/dev/null 2>&1 &
-    EPOPTES_VNCVIEWER_PID="$!"
+    xprop_set EPOPTES_VNCVIEWER_PID "$!"
 }
 
 # The vnc clients should automatically exit when the server is killed.
 # Unfortunately, that isn't always true, so try to kill them anyway.
 stop_receptions() {
-    if [ -n "$EPOPTES_VNCVIEWER_PID" ]; then
-        kill "$EPOPTES_VNCVIEWER_PID"
-        unset EPOPTES_VNCVIEWER_PID
+    local pid
+
+    unset receiving_broadcast
+    ensure_display
+    pid=$(xprop_get EPOPTES_VNCVIEWER_PID)
+    if [ -n "$pid" ]; then
+        kill "$pid"
+        xprop_unset EPOPTES_VNCVIEWER_PID
     fi
 }
 
@@ -295,9 +422,8 @@ root_term() {
 # $1 = port.
 remote_term() {
     local screen_params
-    REM=$1
+
     if [ "$UID" -eq 0 ]; then
-	REM="$SERVER:${1#*:}"
         screen_params="bash -l"
     else
         screen_params="-l"
@@ -305,7 +431,7 @@ remote_term() {
     background sh -c "
 cd
 sleep 1
-TERM=xterm exec socat EXEC:'screen $screen_params',pty,stderr tcp:$REM"
+TERM=xterm exec socat EXEC:'screen $screen_params',pty,stderr tcp:$SERVER:$1"
 }
 
 # Ping is called every few seconds just to make sure the connection is alive.
@@ -314,7 +440,10 @@ TERM=xterm exec socat EXEC:'screen $screen_params',pty,stderr tcp:$REM"
 # exit automatically, so tell it to exit as soon as X is unavailable.
 ping() {
     if [ "$UID" -gt 0 ]; then
-        xprop -root -f EPOPTES_CLIENT 32c -set EPOPTES_CLIENT $$ || exit
+        xprop -root -f EPOPTES_CLIENT 32c -set EPOPTES_CLIENT $$ || die "No X"
+    fi
+    if [ "$receiving_broadcast" = true ]; then
+        reset_screensaver
     fi
 }
 
@@ -330,15 +459,13 @@ if [ -z "$UID" ] || [ -z "$TYPE" ] || [ -z "$SERVER" ]; then
     die "Required environment variables are missing."
 fi
 
-# Source the lsb init functions, for log_end_msg.
-# Unfortunately it seems that Centos and Fedora don't have that file.
-if [ -f /lib/lsb/init-functions ]; then
-    ( # Use a subshell, we only need init-functions once
-    . /lib/lsb/init-functions
-    log_end_msg 0 >&5
-    )
-else
-    echo "[ OK ]" >&5
-fi
+echo "   ...done" >&5
 
 info
+
+# Prevent dbus from getting autolaunched (issue #66)
+export "DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS:-unix:path=/dev/null}"
+
+for i in 0 15; do
+    trap "on_signal $i" $i
+done
diff --git a/epoptes-client/epoptes-client b/epoptes-client/epoptes-client
--- a/epoptes-client/epoptes-client
+++ b/epoptes-client/epoptes-client
@@ -1,81 +1,25 @@
-#!/bin/bash
+#!/bin/sh
+# This file is part of Epoptes, https://epoptes.org
+# Copyright 2010-2018 the Epoptes team, see AUTHORS.
+# SPDX-License-Identifier: GPL-3.0-or-later
 
-###########################################################################
-# Connects to a remote server and offers it a local shell.
-# Usage: epoptes [server] [port]
-#
-# Copyright (C) 2010-2012 Alkis Georgopoulos <alkisg@gmail.com>
-#
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-#
-# On Debian GNU/Linux systems, the complete text of the GNU General
-# Public License can be found in `/usr/share/common-licenses/GPL'.
-###########################################################################
-
-# epoptes-client may be called either as root, to control the client, or as a
-# user, to control the user session.
-# As root, epoptes-client starts from if-up.d on standalone clients.
-# Unfortunately, thin and fat clients don't get if-up.d events, so just for
-# this case we're using a helper sysvinit script.
-# As a user, epoptes-client runs from /etc/xdg/autostart.
+# epoptes-client is called either from systemd as root, to control the client,
+# or from /etc/xdg/autostart as a user, to control the user session.
 # Users can cancel that from their System > Preferences > Services gnome menu.
-log_file="/tmp/.epoptes_log"
-VERSION=$(lliurex-version)
-download_certificate=False
 
-if [ ! -f $log_file ]; then
-	touch $log_file
-	chmod 777 $log_file 2>/dev/null
-else
-	chmod 777 $log_file 2>/dev/null 
-fi
+usage() {
+    printf "Usage: $0 [-c|-h|-v] [SERVER] [PORT]\n%s" \
+'
+Connect to a remote server and offer it a local shell.
+'
+}
 
-
-discover() {
-	echo "  - Dentro de funcion discover -  " >> $log_file
-	echo >> $log_file
-	MATCH=""
-	if [[ "$VERSION" == *server* ]]
-	then
-		LIGHT=` echo "$DISPLAY" | cut -d ":" -f1`
-		if [[ -z "$LIGHT" ]]; then 
-			MATCH="servidor"
-		else
-			MATCH="ligero"
-		fi
-	else
-		if grep "client" $log_file > /dev/null
-		then
-			if [[ -z "$LTSP_FATCLIENT" ]]; then
-				MATCH="Pesado"
-				download_certificate=True
-			else
-				MATCH="Semiligero"
-				download_certificate=True
-			fi
-		fi
-	fi
-	echo >> $log_file
-	echo "** Soy un $MATCH **" >> $log_file
-	echo >> $log_file
-} 
-
-
+version() {
+    export VERSION="1.0"  # Automatically updated while packaging
+}
 
 die() {
     echo "epoptes-client ERROR: $@" >&2
-    echo "epoptes-client ERROR: $@" >> $log_file
     exit 1
 }
 
@@ -155,73 +99,66 @@ basic_info() {
 
 fetch_certificate()
 {
-    echo "[fetch_certificate] Comprobando el certificado: epoptes-client -c">> $log_file
-    echo "[fetch_certificate]Debe ser 0 sino muere, UID : $UID" >> $log_file
-    test "$UID" -eq 0 || die "[fetch_certificate] Need to be root to fetch the certificate" >> $log_file
+    test "$UID" -eq 0 || die "Need to be root to fetch the certificate"
     mkdir -p /etc/epoptes
     openssl s_client -connect $SERVER:$PORT < /dev/null \
         | sed '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/!d' \
-        > /tmp/.epoptes_server.crt
-    if [ -s /tmp/.epoptes_server.crt ]; then
-	mv /tmp/.epoptes_server.crt /etc/epoptes/server.crt
-        echo "[fetch_certificate] Successfully fetched certificate from $SERVER:$PORT" >> $log_file
-	echo "[fetch_certificate] Successfully fetched certificate from $SERVER:$PORT"
+        > /etc/epoptes/server.crt
+    if [ -s /etc/epoptes/server.crt ]; then
+        echo "Successfully fetched certificate from $SERVER:$PORT"
         exit 0
     else
-	rm -rf /tmp/.epoptes_server.crt || true
-	echo  "[fetch_certificate] FIRST Failed to fetch certificate from $SERVER:$PORT" >> $log_file
-	sleep 10
-	openssl s_client -connect $SERVER:$PORT < /dev/null \
-        | sed '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/!d' \
-        > /tmp/.epoptes_server.crt
-	 if [ -s /tmp/.epoptes_server.crt ]; then
-		mv /tmp/.epoptes_server.crt /etc/epoptes/server.crt
-		echo "[fetch_certificate] Successfully fetched certificate from $SERVER:$PORT" >> $log_file
-		echo "[fetch_certificate] Successfully fetched certificate from $SERVER:$PORT"
-		exit 0
-	else
-		rm -rf /tmp/.epoptes_server.crt || true
-		die "[fetch_certificate] SECOND Failed to fetch certificate from $SERVER:$PORT"
-	fi
-	
+        die "Failed to fetch certificate from $SERVER:$PORT"
     fi
 }
 
-fetch_certificate_download()
-{
-    echo "[fetch_certificate_download] FORZANDO EL DOWNLOAD DEL CERTIFICADO">> $log_file
-    echo "[fetch_certificate_download] Comprobando el certificado">> $log_file
-    echo "[fetch_certificate_download] Debe ser 0 sino muere, UID : $UID" >> $log_file
-    test "$UID" -eq 0 || die "[fetch_certificate_download] Need to be root to fetch the certificate" >> $log_file
-    mkdir -p /etc/epoptes
-    openssl s_client -connect $SERVER:$PORT < /dev/null \
-        | sed '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/!d' \
-        > /tmp/.epoptes_server.crt
-    if [ -s /tmp/.epoptes_server.crt ]; then
-	mv /tmp/.epoptes_server.crt /etc/epoptes/server.crt
-        echo "[fetch_certificate_download] Successfully fetched certificate from $SERVER:$PORT" >> $log_file
-	echo "[fetch_certificate_download] Successfully fetched certificate from $SERVER:$PORT"
-    else
-	rm -rf /tmp/.epoptes_server.crt || true
-	echo  "[fetch_certificate_download] FIRST Failed to fetch certificate from $SERVER:$PORT" >> $log_file
-	sleep 10
-	openssl s_client -connect $SERVER:$PORT < /dev/null \
-        | sed '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/!d' \
-        > /tmp/.epoptes_server.crt
-	 if [ -s /tmp/.epoptes_server.crt ]; then
-		mv /tmp/.epoptes_server.crt /etc/epoptes/server.crt
-		echo "[fetch_certificate_download] Successfully fetched certificate from $SERVER:$PORT" >> $log_file
-		echo "[fetch_certificate_download] Successfully fetched certificate from $SERVER:$PORT"
-	else
-		rm -rf /tmp/.epoptes_server.crt || true
-		die "[fetch_certificate_download] SECOND Failed to fetch certificate from $SERVER:$PORT"
-	fi
-	
+wait_for_dns() {
+    # Don't wait for DNS if SERVER is an IP
+    if [ -z "$(echo "$SERVER" | tr -d '[0-9.]')" ]; then
+        server_ip=$SERVER
+        return
+    fi
+    delay=60
+    while true; do
+        server_ip=$(getent hosts "$SERVER" | awk '{ print $1; exit }')
+        test -n "$server_ip" && break
+        # If DNS is not up yet, retry, otherwise abort
+        server_ip=$(getent hosts "ntp.org" | awk '{ print $1; exit }')
+        if [ -z "$server_ip" ]; then
+            echo "Cannot resolve $SERVER, postponing for $delay seconds..."
+            sleep $delay
+            # Add a minute for each failure to minimize log spamming
+            delay=$(($delay+60))
+        else
+            echo "Cannot resolve $SERVER while DNS appears to work, aborting."
+            exit 1
+        fi
+    done
+}
+
+apply_wol() {
+    if [ "$UID" -eq 0 ] && [ -n "$WOL" ] && [ -x /sbin/ethtool ] &&
+        [ "$EPOPTES_CLIENT_APPLIED_WOL" != True ]
+    then
+        export EPOPTES_CLIENT_APPLIED_WOL=True
+        # Copied from client-functions, these map from server_ip to def_iface
+        read def_iface IP <<EOF
+$(ip route get "$server_ip" | sed -n 's/.*dev *\([^ ]*\).*src *\([^ ]*\).*/\1 \2/p')
+EOF
+        test "${def_iface:-lo}" != "lo" || read def_iface IP <<EOF
+$(ip route get 192.168.67.0 | sed -n 's/.*dev *\([^ ]*\).*src *\([^ ]*\).*/\1 \2/p')
+EOF
+        if [ "${def_iface:-lo}" != "lo" ]; then
+            # Only set WOL if def_iface is both != '' and != 'lo'.
+            echo "Setting WOL=$WOL for $def_iface"
+            ethtool -s "$def_iface" wol $WOL
+        fi
     fi
 }
 
 
-# Main.############################################
+# Main.
+version
 
 # Check the first parameter as it may turn out we don't need to run at all
 case "$1" in
@@ -233,55 +170,18 @@ case "$1" in
         if [ -x /usr/bin/man ]; then
             exec man epoptes-client
         else
-            echo "Usage: $0 [-c|-h|-v] [SERVER] [PORT]"
-            exit 0
+            usage
+            exit
         fi
         ;;
     -c|--certificate)
-        need_certificate=True
+        need_certificate=true
         shift
         ;;
 esac
 
-echo "">> $log_file
-echo "*******DEPURANDO SCRIPT /USR/SBIN/EPOPTES PARA EL *************    USUARIO : $USER      ******">> $log_file
-echo "">> $log_file
-date >> $log_file
-echo "">> $log_file
-echo "$VERSION" >> $log_file
-echo "">> $log_file
-echo "_________MAIN_____________">> $log_file
-discover
-echo "Presesion Lightdm.........."  >> $log_file
-echo "">> $log_file
-name_aux=$(date | awk '{print $4}')
-file_socat="/tmp/.epoptes_socat_$name_aux"
-file_socat_post="/tmp/.epoptes_socat_post_$name_aux"
-ps aux | grep /usr/sbin/epoptes | grep -v root | grep -v "grep" >> $log_file
-ps aux | grep /usr/sbin/epoptes | grep -v root | grep -v "grep"  | awk '{print $2}' | uniq > $file_socat
-cat $file_socat >> $log_file
-USERS_SOCAT=$(wc -l < $file_socat)
-#USERS_SOCAT=$(ps aux | grep /usr/sbin/epoptes | grep -v "root" | grep -v "grep" | awk '{print $2}' | uniq | wc -l)
-echo "USERS_SOCAT = $USERS_SOCAT">> $log_file;
-if [[ "$MATCH" != ligero  ]]; then
-	if (("$USERS_SOCAT" > 2 )); then
-		echo "Estoy dentro del if matando procesos.......">> $log_file
-		for i in $(ps aux | grep /usr/sbin/epoptes | grep -v "root" | grep -v "grep" | awk '{print $2}' | uniq); do
-			echo "Dentro del FOR para .......">> $log_file
-			ps -aux | grep $i >> $log_file
-			echo "Matando el proceso $i"  >> $log_file
-			kill -9 $i >> $log_file
-		done
-	fi
-fi
-
-
-export VERSION="0.5.7" # Automatically updated by mkdst
-
-
-
-# When called from /etc/xdg/autostart, /sbin is not in the system path.
-PATH="$PATH:/sbin:/usr/sbin"
+# Set a reasonable PATH to execute commands or to relaunch epoptes-client.
+export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
 
 # When launched as a service, LANG might not be set.
 if [ -z "$LANG" ] && [ -r /etc/default/locale ]; then
@@ -290,7 +190,6 @@ if [ -z "$LANG" ] && [ -r /etc/default/locale ]; then
 fi
 
 basic_info
-echo "Capturo basic info UID:$UID TYPE:$TYPE SERVER:$SERVER PORT:$PORT">> $log_file
 # The configuration file overrides the default values
 if [ -f /etc/default/epoptes-client ]; then
     . /etc/default/epoptes-client
@@ -302,30 +201,11 @@ export PORT=${2:-$PORT}
 # Provide an easy way to fetch the server certificate
 test -n "$need_certificate" && fetch_certificate
 
-#Nos aseguramos de tener el certificado del server
-echo "Necesito el certificado -> $download_certificate" >> $log_file
-BAJAR_CERT=True
-if [ $download_certificate  =  $BAJAR_CERT ];then
-        echo "Compruebo si el certificado existe..... ">> $log_file
-        if [ ! -s /etc/epoptes/server.crt ]; then
-               echo "FORZADO -> No tengo el certificado debo adquirirlo del server" >> $log_file
-               fetch_certificate_download
-	else
-		echo "Tengo el certificado continua la ejecucion....." >> $log_file
-        fi
-fi
-
 # We don't want the epoptes-client system service running on the epoptes server
 if ( [ $UID -eq 0 ] && [ $TYPE = "standalone" ] && [ -x /usr/bin/epoptes ] ) ||
     chrooted
 then
-   echo "--Parte del chrooted--" >> $log_file
-   if lliurex-version -t client; then
-	echo "Compruebo como TRUE --> lliurex-version -t client" >> $log_file
-   else
-	echo "FIN compruebo como FALSE --> lliurex-version -t client" >> $log_file
-	exit 0
-   fi
+    exit 0
 fi
 
 # Go to the scripts directory, so that we can run them with ./xxx
@@ -336,29 +216,19 @@ else
     cd /usr/share/epoptes-client
 fi
 
-# Source the lsb init functions, for log_begin_msg.
-# Unfortunately it seems that Centos and Fedora don't have that file.
-if [ -f /lib/lsb/init-functions ]; then
-    . /lib/lsb/init-functions
-else
-    alias log_begin_msg="echo -n"
-fi
-log_begin_msg "Epoptes-client connecting to $SERVER:$PORT..."
-echo "Epoptes-client connecting to $SERVER:$PORT..."
-echo "Epoptes-client connecting to $SERVER:$PORT...">>$log_file
+wait_for_dns
+apply_wol
+printf "Epoptes-client connecting to $SERVER:$PORT..."
+
 # Call chain:
-#  * if-up.d executes /usr/sbin/epoptes-client
+#  * systemd executes /usr/sbin/epoptes-client
 #  * then socat is called
 #  * after a successful connection, socat exec's /bin/sh
 #  * and the daemon sends /usr/share/epoptes/client-functions to that shell
 
 # Kill all ghost instances of epoptes-client of the same user.
-# That may happen if network connectivity is lost for a while.
-# Standalone workstations don't hang if the network is down, and nbd might cope
-# with that for LTSP clients, but epoptes kills disconnected epoptes-clients.
 # The current epoptes-client is excluded because it starts with /bin/sh.
-echo "pkill de $UID">>$log_file
-pkill -U $UID -f '^epoptes-client$'
+pkill -QUIT -U "$UID" -f '^epoptes-client$'
 
 # Remember the stdout descriptor to use it in the second phase.
 # stdio will be redirected to the server, but stderr will be kept in the
@@ -374,93 +244,24 @@ cmdline='bash -c \"exec -a epoptes-client sh\"'
 # Offer an lts.conf (or environment) variable to disable cert verification.
 if my_boolean_is_true "${EPOPTES_CLIENT_VERIFY_CERTIFICATE:-True}"; then
     cert_param="cafile=/etc/epoptes/server.crt"
+    # Check if socat provides the commonname option and use it in order to
+    # support certificates which don't have a commonname set
+    if socat -hhh | grep -q openssl-commonname; then
+        cert_param="$cert_param,commonname=\"\""
+    fi
 else
     cert_param="verify=0"
 fi
 
 # Connect to the server, or keep retrying until the server gets online
 # (for standalone workstations booted before the server).
-RUN=1
-salida(){
-	RUN=0
-	echo "Estoy en la funcion de SALIDA de $USER" >> $log_file
-	date >> $log_file
-	echo "Quiero matar el proceso $BASHPID" >> $log_file
-	#kill -9 $BASHPID
-}
-echo "RUN = $RUN"
-test_conn(){
-    echo "Testeando la funcion CONN $USER">> $log_file
-    if [ -z ${LTSP_CLIENT} ]; then
-	echo "No es cliente LTSP">> $log_file
-	#exit 0
-	#RUN=0
-	return 0
-    fi
-    ping -c 2 ${LTSP_CLIENT}
-    if [ $? -eq 0 ]; then
-	echo "Estamos en if del ping -c">> $log_file
-	#exit 0
-	return 0
-    fi
-    echo "Vamos a salida -- No detecte nada en funcion CONN">> $log_file
-    salida
-}
-
-trap salida KILL TERM QUIT INT STOP EXIT
-echo "__________________________________________________">>$log_file
-echo "">>$log_file
-echo "-- Funcion Principal para abrir el SOCAT --" >> $log_file
 if [ -s /etc/epoptes/server.crt ] || [ "$cert_param" = "verify=0" ]; then
-   echo "Dentro del if antes del while 1 del usuario $USER" >> $log_file
-   while [ ${RUN} -eq 1 ] && sleep 1; do
-	ALIVE=$(ps ax|grep $PPID|grep -v grep|wc -l)
-	echo "Dentro del While porque el RUN es $RUN para usuario $USER">> $log_file
-	ps aux | grep /usr/sbin/epoptes | grep -v root | grep -v "grep"  | awk '{print $2}' | uniq > $file_socat_post
-	echo "   - USERS_SOCAT_POST - ">>$log_file
-	cat $file_socat_post >> $log_file
-	USERS_SOCAT_POST=$(wc -l < $file_socat_post)
-	#USERS_SOCAT_POST=`ps aux | grep /usr/sbin/epoptes | grep -v root | grep -v "grep" | awk '{print $2}' | uniq | wc -l `
-	echo "Calculando el USERS_SOCAT_POST: $USERS_SOCAT_POST" >> $log_file
-	if (( $USERS_SOCAT_POST < 3 )) || [[ "$MATCH" == "ligero" ]]; then
-		echo "-----SOCAT se va a ejecutar para el usuario: $USER -----">> $log_file
-		sleep 20
-		date_create=$(date)
-		echo "socat openssl-connect:$SERVER:$PORT,$cert_param,interval=60,forever EXEC:'$cmdline',sigint,sigquit,sigterm" >> $log_file
-		socat openssl-connect:$SERVER:$PORT,$cert_param,interval=60,forever EXEC:"$cmdline",sigint,sigquit
-		echo "-------------------------------------" $log_file
-		echo "Muere el SOCAT del usuario: $USER creado: $date_create">> $log_file
-		date >> $log_file
-		echo "-------------------------------------" $log_file
-	fi
-	
-	if [ "x${ALIVE}" != "x1" ]; then 
-	    	echo "Se aborta el script para el usuario $USER debido al AlIVE">> $log_file
-		exit 1
-	fi
-	echo "Paso del ALIVE y continuo porque RUN: $RUN del usuario $USER">> $log_file
-	test_conn
-	SESSION_GNOME=`ps aux | grep mate-session | wc -l `
-	if (( $SESSION_GNOME < 2 )); then
-		date >> $log_file
-		echo "La sesion no esta activa me quedo en la sesion MATE-SESSION: $SESSION_GNOME modifico el RUN" >> $log_file
-		RUN=0
-	fi
-    done;
+    exec socat -T 60 openssl-connect:$SERVER:$PORT,$cert_param,interval=60,forever EXEC:"$cmdline"
 elif [ -f /etc/epoptes/server.crt ]; then
-	echo "Antes del while2 del user: $USER" >> $log_file
-    while [ ${RUN} -eq 1 ] && sleep 1; do
-	ALIVE=$(ps ax|grep $PPID|grep -v grep|wc -l)
-	socat tcp:$SERVER:$PORT,interval=60,forever EXEC:"$cmdline",nofork
-	if [ "x${ALIVE}" != "x1" ]; then 
-	    exit 1
-	fi
-	echo "RUN en ELIF es $RUN del usuario $USER">> $log_file
-	test_conn
-    done;
+   exec socat tcp:$SERVER:$PORT,interval=60,forever EXEC:"$cmdline",nofork
 else
-	echo "en el else del usuario $USER">> $log_file
-    $0 -c
-    exec $0
+    die "
+The epoptes certificate file, /etc/epoptes/server.crt, doesn't exist.
+You can fetch the server certificate by running:
+$0 -c"
 fi
-echo "____________FIN_______SCRIPT____________">> $log_file
diff --git a/epoptes-client/get-display b/epoptes-client/get-display
--- a/epoptes-client/get-display
+++ b/epoptes-client/get-display
@@ -1,27 +1,20 @@
 #!/bin/sh
-###########################################################################
-# Output DISPLAY and XAUTHORITY for the current user's X screen.
-# A root user can then use those to access the user's display.
-# Usage: export $(get-display)
-#
-# Copyright (C) 2012 Alkis Georgopoulos <alkisg@gmail.com>
-#
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-#
-# On Debian GNU/Linux systems, the complete text of the GNU General
-# Public License can be found in `/usr/share/common-licenses/GPL'.
-###########################################################################
+# This file is part of Epoptes, https://epoptes.org
+# Copyright 2012-2018 the Epoptes team, see AUTHORS.
+# SPDX-License-Identifier: GPL-3.0-or-later
+
+usage() {
+    printf "Usage: export \$($0)\n%s" \
+"
+Output DISPLAY and XAUTHORITY for the current user's X screen.
+A root user can then use those to access the user's display.
+"
+}
+
+die() {
+    printf "%s\n" "$@" >&2
+    exit 1
+}
 
 exit_if_found() {
     # Check if DISPLAY/XAUTHORITY are valid.
@@ -38,42 +31,51 @@ exit_if_found() {
     fi
 }
 
+if [ $# -gt 0 ]; then
+    die "$(usage)"
+fi
+
 # Plan A: check if the variables are already set
 exit_if_found
 
-# Plan B: check if we can get the info from some running process
-for p in $(pgrep -x 'ldm|gdmgreeter|kdm_greet|lxdm-greeter-gt|dbus-daemon'); do
+# Plan B: check if we can get the info from some well-known process
+# Oneliner to discover suitable processes:
+# ps -o pid,user:13,comm,cmd $(grep -sl DISPLAY= /proc/[0-9]*/environ |
+#     cut -d/ -f3) | sort -n | less
+# Tests on Ubuntu 18.04 and some other distros:
+# LTSP greeter: ldm
+# Ubuntu greeter: dbus-daemon|pulseaudio (same in Fedora and CentOS)
+# Ubuntu session: dbus-daemon|pulseaudio (same when locked)
+# Ubuntu MATE greeter: lightdm-greeter
+# Ubuntu MATE session: dbus-daemon|pulseaudio (same when locked)
+# Kubuntu greeter: sddm-greeter|dbus-daemon|pulseaudio
+# Kubuntu session: dconf-service|dbus-daemon|pulseaudio (same when locked)
+# Lubuntu greeter: lightdm-greeter (same when locked)
+# Lubuntu session: dconf-service|pulseaudio (no dbus!)
+# Xubuntu greeter: lightdm-greeter (same when locked)
+# Xubuntu session: dconf-service|dbus-daemon|pulseaudio (no root process!)
+# Sylvia greeter: lightdm-greeter|dbus-daemon
+# Sylvia session: dbus-daemon|pulseaudio (same when locked)
+# Debian stretch MATE greeter: lightdm-gtk-gre|dbus-daemon
+# Debian stretch MATE session: dbus-daemon|dconf-service|pulseaudio
+for p in $(pgrep -x 'ldm|lightdm-greeter|dbus-daemon|dconf-service|pulseaudio' |
+    sort -rn)
+do
     # The first DISPLAY= is only there to prevent a possible syntax error
     export DISPLAY="$DISPLAY" $(tr '\0' '\n' 2>/dev/null < /proc/$p/environ |
         egrep '^DISPLAY=|^XAUTHORITY=')
     exit_if_found
 done
 
-# Plan C: try ck-list-sessions
-while read var equals value; do
-    case "$var" in
-        Session*)
-            unset USER DISPLAY XAUTHORITY
-            ;;
-        unix-user)
-            value=${value%\'}
-            USER=${value#\'}
-            ;;
-        x11-display)
-            value=${value%\'}
-            DISPLAY=${value#\'}
-            if [ -n "$DISPLAY" ]; then
-                XAUTHORITY="$(getent passwd "$USER" | cut -d: -f6)/.Xauthority"
-                exit_if_found
-            fi            
-            ;;
-    esac
-done <<EOF
-$(ck-list-sessions)
-EOF
+# Plan C: Try all processes!
+for p in $(pgrep '' | sort -rn); do
+    # The first DISPLAY= is only there to prevent a possible syntax error
+    export DISPLAY="$DISPLAY" $(tr '\0' '\n' 2>/dev/null < /proc/$p/environ |
+        egrep '^DISPLAY=|^XAUTHORITY=')
+    exit_if_found
+done
 
 # Plan D: give up!
-echo "Could not detect or access the active display" >&2
 echo "DISPLAY=
 XAUTHORITY="
-exit 1
+die "Could not detect or access the active display"
